name: Git push
description: Git pushを実行するアクションです。

inputs:
  commit-message:
    description: コミットメッセージ。
    required: true

runs:
  using: composite
  steps:
    - name: Git push
      shell: pwsh
      env:
        COMMIT_MESSAGE: ${{ inputs.commit-message }}
      run: |
        $parameters = @{
          CommitMessage = $Env:COMMIT_MESSAGE
        }
        ${{ github.action_path }}/GitPush.ps1 @parameters -Verbose -ErrorAction Stop
