name: Git push
description: Git pushを実行するGitHub Actionです。

inputs:
  commit-message:
    description: コミットメッセージ。
    required: true

runs:
  using: composite
  steps:
    - name: Git push
      shell: pwsh
      run: |
        ${{ github.action_path }}/GitPush.ps1 `
            -CommitMessage '${{ inputs.commit-message }}' `
            -Verbose `
            -ErrorAction Stop
