version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    labels:
      - dependencies

  - package-ecosystem: github-actions
    directories:
      - /.github/actions/check-extension
      - /.github/actions/compress-archive
      - /.github/actions/copy-github-labels
      - /.github/actions/create-pull-request
      - /.github/actions/dotnet-pack
      - /.github/actions/dotnet-publish
      - /.github/actions/get-dotnet-projects
      - /.github/actions/get-github-repositories
      - /.github/actions/git-push
      - /.github/actions/git-versioning
      - /.github/actions/pascal-to-kebab
      - /.github/actions/read-file
      - /.github/actions/run-msbuild-target
      - /.github/actions/sync-repositories
      - /.github/actions/upload-release-assets
    schedule:
      interval: daily
    labels:
      - dependencies
