version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    labels:
      - dependencies

  - package-ecosystem: github-actions
    directory: /.github/actions
    schedule:
      interval: daily
    labels:
      - dependencies
