name: Get .NET projects
description: .NETプロジェクトの情報を取得するアクションです。

inputs:
  solution-name:
    description: ソリューション名。
    required: false
    type: string
    default: ${{ github.event.repository.name }}
  projects:
    description: 「プロジェクト名,プラットフォーム名」区切りのリスト。
    required: true
    type: string
  settings-file-path:
    description: 設定ファイルのパス。
    required: false
    type: string
    default: ${{ github.action_path }}/default.json

outputs:
  projects:
    description: upload-artifacts-dotnet.ymlワークフローの引数となるJSON文字列を出力する。
    value: ${{ steps.x.outputs.projects }}

runs:
  using: composite
  steps:
    - name: Get .NET projects
      id: x
      shell: pwsh
      run: |
        ${{ github.action_path }}/GetDotNetProjects.ps1 `
            -SolutionName '${{ inputs.solution-name }}' `
            -Projects '${{ inputs.projects }}' `
            -Verbose `
            -ErrorAction Stop
