name: Compress archive
description: 圧縮されたアーカイブを作成するアクションです。

inputs:
  path:
    description: 圧縮対象のファイルが存在するディレクトリ。
    required: true
  type:
    description: 圧縮形式。
    required: false
    default: zip
  destination-path:
    description: rootがtrueの場合は、出力先ファイルパス。falseの場合は、出力先ディレクトリ。
    required: true
  root:
    description: path内のディレクトリ毎にzipファイルを作成するかどうか。
    required: false
    default: 'true'
  suffix:
    description: zipファイル名の末尾に追加する文字列。rootがfalseの場合のみ有効。
    required: false
    default: ''
  exclude:
    description: ディレクトリ内のファイルが1個の場合、圧縮対象とせずコピーを行うファイルのリスト。rootがfalseの場合のみ有効。
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Compress archive
      shell: pwsh
      env:
        TARGET_PATH: ${{ inputs.path }}
        TYPE: ${{ inputs.type }}
        DESTINATION_PATH: ${{ inputs.destination-path }}
        ROOT: ${{ inputs.root }}
        SUFFIX: ${{ inputs.root != 'true' && inputs.suffix || '' }}
        EXCLUDE: ${{ inputs.root != 'true' && inputs.exclude || '' }}
      run: |
        $parameters = @{
          Path = $Env:TARGET_PATH
          Type = $Env:TYPE
          Suffix = $Env:SUFFIX
          Exclude = $Env:EXCLUDE
        }
        $parameters[$Env:ROOT -eq 'true' ? 'DestinationFilePath' : 'DestinationDirectoryPath'] = $Env:DESTINATION_PATH

        ${{ github.action_path }}/CompressArchive.ps1 @parameters -Verbose -ErrorAction Stop
