name: Compress archive
description: zipファイルを作成するGitHub Actionです。

inputs:
  path:
    description: 圧縮対象のファイルが存在するディレクトリ。
    required: true
  destination-path:
    description: rootがtrueの場合は、出力先ファイルパス。falseの場合は、出力先ディレクトリ。
    required: true
  root:
    description: path内のディレクトリ毎にzipファイルを作成するかどうか。
    required: false
    default: true
  suffix:
    description: zipファイル名の末尾に追加する文字列。rootがfalseの場合のみ有効。
    required: false
    default: null

runs:
  using: composite
  steps:
    - name: Compress archive
      shell: pwsh
      run: |
        ${{ github.action_path }}/CompressArchive.ps1 `
            -Path '${{ inputs.path }}' `
            '${{ inputs.root == 'true' && '' || join('-DestinationFilePath', inputs.destination-path, ' ') }}' `
            '${{ inputs.root != 'true' && '' || join('-DestinationDirectoryPath', inputs.destination-path, ' ') }}' `
            -Suffix '${{ inputs.suffix }}' `
            -Verbose `
            -ErrorAction Stop
