name: Compress archive
description: 圧縮されたアーカイブを作成するアクションです。

inputs:
  path:
    description: 圧縮対象のファイルが存在するディレクトリ。
    required: true
    type: string
  type:
    description: 圧縮形式。
    required: false
    type: choice
    options:
      - zip
      - gzip
    default: zip
  destination-path:
    description: rootがtrueの場合は、出力先ファイルパス。falseの場合は、出力先ディレクトリ。
    required: true
    type: string
  root:
    description: path内のディレクトリ毎にzipファイルを作成するかどうか。
    required: false
    type: boolean
    default: true
  suffix:
    description: zipファイル名の末尾に追加する文字列。rootがfalseの場合のみ有効。
    required: false
    type: string
    default: null
  exclude:
    description: ディレクトリ内のファイルが1個の場合、圧縮対象とせずコピーを行うファイルのリスト。rootがfalseの場合のみ有効。
    required: false
    type: string
    default: null

runs:
  using: composite
  steps:
    - name: Compress archive
      shell: pwsh
      env:
        DESTINATION_FILE_PARAMETER: ${{ format('-DestinationFilePath "{0}"', inputs.destination-path) }}
        DESTINATION_DIRECTORY_PARAMETER: ${{ format('-DestinationDirectoryPath "{0}"', inputs.destination-path) }}
        SUFFIX_PARAMETER: ${{ format('-Suffix "{0}"', inputs.suffix) }}
        EXCLUDE_PARAMETER: ${{ format('-Exclude "{0}"', inputs.exclude) }}
      run: |
        ${{ github.action_path }}/CompressArchive.ps1 `
            -Path '${{ inputs.path }}' `
            -Type '${{ inputs.type }}' `
            ${{ inputs.root == 'true' && env.DESTINATION_FILE_PARAMETER || env.DESTINATION_DIRECTORY_PARAMETER }} `
            ${{ inputs.root != 'true' && env.SUFFIX_PARAMETER || '' }} `
            ${{ inputs.root != 'true' && env.EXCLUDE_PARAMETER || '' }} `
            -Verbose `
            -ErrorAction Stop
