name: Compress archive
description: zipファイルを作成するGitHub Actionです。

inputs:
  path:
    description: 圧縮対象のファイルが存在するディレクトリ。
    required: true
  destination-path:
    description: rootがtrueの場合は、出力先ファイルパス。falseの場合は、出力先ディレクトリ。
    required: true
  root:
    description: path内のディレクトリ毎にzipファイルを作成するかどうか。
    required: false
    default: true
  suffix:
    description: zipファイル名の末尾に追加する文字列。rootがfalseの場合のみ有効。
    required: false
    default: null

runs:
  using: composite
  steps:
    - name: Compress archive
      shell: pwsh
      env:
        DESTINATION_FILE_PARAMETER: ${{ format('-DestinationFilePath "{0}"', inputs.destination-path) }}
        DESTINATION_DIRECTORY_PARAMETER: ${{ format('-DestinationDirectoryPath "{0}"', inputs.destination-path) }}
      run: |
        ${{ github.action_path }}/CompressArchive.ps1 `
            -Path '${{ inputs.path }}' `
            ${{ inputs.root == 'true' && '' || env.DESTINATION_FILE_PARAMETER }} `
            ${{ inputs.root != 'true' && '' || env.DESTINATION_DIRECTORY_PARAMETER }} `
            -Suffix '${{ inputs.suffix }}' `
            -Verbose `
            -ErrorAction Stop
