name: Git versioning
description: バージョン情報を取得するアクションです。

inputs:
  file-name:
    description: バージョンを設定しているJSONファイルの名前。
    required: false
    type: string
    default: version.json
  hash:
    description: 基点とするコミットハッシュ値。このハッシュ値以降のコミットで、JSONファイルが更新されている場合は安定版リリースとなり、リビジョン番号を省略したバージョン形式となる。
    required: false
    type: string
    default: ${{ github.sha }}
  revision:
    description: リビジョン番号を表す数値。
    required: false
    type: number
    default: ${{ github.run_number }}

outputs:
  version:
    description: バージョンを表す文字列。
    value: ${{ steps.x.outputs.version }}
  version-major:
    description: メジャー番号を表す数値。
    value: ${{ steps.x.outputs.version-major }}
  version-minor:
    description: マイナー番号を表す数値。
    value: ${{ steps.x.outputs.version-minor }}
  version-build:
    description: ビルド番号を表す数値。
    value: ${{ steps.x.outputs.version-build }}
  version-revision:
    description: リビジョン番号を表す数値。
    value: ${{ steps.x.outputs.version-revision }}
  release:
    description: 安定版リリースかどうか。
    value: ${{ steps.x.outputs.release }}

runs:
  using: composite
  steps:
    - name: Get version
      id: x
      shell: pwsh
      run: |
        ${{ github.action_path }}/Version.ps1 `
            -VersionFileName '${{ inputs.file-name }}' `
            -Hash '${{ inputs.hash }}' `
            -Revision ${{ inputs.revision }} `
            -Verbose `
            -ErrorAction Stop
