name: .NET Pack and NuGet Push
description: dotnet packとnuget pushコマンドを実行するアクションです。

inputs:
  dotnet-version:
    description: インストールする.NET SDKバージョン。
    required: false
    default: 10.0.100-rc.1.25451.107
  configuration:
    description: ビルド構成。
    required: false
    default: Release
  version:
    description: バージョンを表す文字列。
    required: true
  output-directory:
    description: 出力先ディレクトリ。
    required: false
    default: pack
  release:
    description: 安定版リリースかどうか。
    required: true
  nuget-user:
    description: NuGetのユーザー名。
    required: false
    default: ${{ github.repository_owner }}

runs:
  using: composite
  steps:
    - name: .NET Pack
      id: pack
      uses: finphie/Actions/.github/actions/dotnet-pack@main
      with:
        dotnet-version: ${{ inputs.dotnet-version }}
        configuration: ${{ inputs.configuration }}
        version: ${{ inputs.version }}
        output-directory: ${{ inputs.output-directory }}

    - name: NuGet Login
      id: login
      if: &nuget
        steps.pack.outputs.success == 'true' && inputs.release
      uses: NuGet/login@d22cc5f58ff5b88bf9bd452535b4335137e24544 # v1
      with:
        user: ${{ inputs.nuget-user }}

    - name: Push(Azure Artifacts)
      if: steps.pack.outputs.success == 'true'
      shell: pwsh
      run: |
        dotnet nuget update source $Env:SOURCE --username ${{ github.repository_owner }} --password $Env:AZURE_ARTIFACT_PAT
        dotnet nuget push "${{ inputs.output-directory }}/**/*.nupkg" --api-key $Env:AZURE_ARTIFACT_PAT --skip-duplicate --source $Env:SOURCE
      env:
        SOURCE: Azure

    - name: Push(NuGet)
      if: *nuget
      shell: pwsh
      run: dotnet nuget push "${{ inputs.output-directory }}/**/*.nupkg" --api-key $Env:TOKEN --skip-duplicate --source $Env:SOURCE
      env:
        SOURCE: NuGet
        TOKEN: ${{ steps.login.outputs.NUGET_API_KEY }}
