name: Create release
description: リリースを作成するアクションです。

inputs:
  title:
    description: リリースのタイトル。
    required: true
  tag:
    description: 対象のgitタグ。
    required: true
  files:
    description: アップロード対象のファイルリスト。
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Create release
      shell: pwsh
      working-directory: ${{ inputs.path }}
      env:
        TITLE: ${{ inputs.title }}
        TAG: ${{ inputs.tag }}
        FILES: ${{ inputs.files }}
      run: |
        $parameters = @{ 
          Title = $Env:TITLE
          Tag = $Env:TAG
          Files = $Env:FILES
        }
        ${{ github.action_path }}/CreateRelease.ps1 @parameters -Verbose -ErrorAction Stop
