name: .NET Publish
description: dotnet publishコマンドを実行するアクションです。

inputs:
  dotnet-version:
    description: インストールする.NET SDKバージョン。
    required: false
    default: 10.0.100-preview.7.25380.108
  project:
    description: プロジェクト名。
    required: true
  configuration:
    description: ビルド構成。
    required: false
    default: Release
  version:
    description: バージョンを表す文字列。
    required: true
  target-framework-moniker:
    description: ターゲットフレームワーク。
    required: false
    default: net9.0
  target-platform-identifier:
    description: プラットフォーム識別子。
    required: false
    default: none
  target-platform-version:
    description: プラットフォームバージョンを表す文字列。
    required: false
    default: ''
  runtime:
    description: ランタイム識別子。
    required: true
  workload-restore:
    description: dotnet workload restoreを実行するかどうか。
    required: false
    default: 'false'
  output-directory:
    description: 出力先ディレクトリ。
    required: false
    default: publish

runs:
  using: composite
  steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 # v4.3.1
      with:
        dotnet-version: ${{ inputs.dotnet-version }}

    - name: Workload restore
      if: inputs.workload-restore == 'true'
      shell: pwsh
      run: dotnet workload restore

    - name: Publish
      shell: pwsh
      env:
        DOTNET_NOLOGO: true
        DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
        DOTNET_CLI_TELEMETRY_OPTOUT: true
        FRAMEWORK: ${{ inputs.target-framework-moniker }}${{ inputs.target-platform-identifier != 'none' && format('-{0}{1}', inputs.target-platform-identifier, inputs.target-platform-version) || '' }}
      run: |
        dotnet publish Source/${{ inputs.project }}/${{ inputs.project }}.csproj `
            --configuration '${{ inputs.configuration }}' `
            --framework '${{ env.FRAMEWORK }}' `
            --runtime '${{ inputs.runtime }}' `
            --output '${{ inputs.output-directory }}' `
            -p:Version=${{ inputs.version }}
