name: Copy GitHub labels
description: GitHubラベルをソース元のリポジトリからコピーするアクションです。

inputs:
  repositories:
    description: リポジトリのリスト。
    required: true
  source-repository:
    description: ソース元のリポジトリ。
    required: true
  delete:
    description: 既存のラベルを削除するかどうか。
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    - name: Copy GitHub labels
      shell: pwsh
      run: |
        ${{ github.action_path }}/CopyGitHubLabels.ps1 `
            -Repositories '${{ inputs.repositories }}' `
            -SourceRepository '${{ inputs.source-repository }}' `
            ${{ inputs.delete == 'true' && '-Delete' || '' }} `
            -Verbose `
            -ErrorAction Stop
