name: Copy GitHub labels
description: GitHubラベルをソース元のリポジトリからコピーするアクションです。

inputs:
  repositories:
    description: リポジトリのリスト。
    required: true
    type: string
  source-repository:
    description: ソース元のリポジトリ。
    required: true
    type: string

runs:
  using: composite
  steps:
    - name: Copy GitHub labels
      shell: pwsh
      run: |
        ${{ github.action_path }}/CopyGitHubLabels.ps1 `
            -Repositories '${{ inputs.repositories }}' `
            -SourceRepository '${{ inputs.source-repository }}' `
            -Verbose `
            -ErrorAction Stop
