name: Copy GitHub labels
description: GitHubラベルをソース元のリポジトリからコピーするアクションです。

inputs:
  repositories:
    description: リポジトリのリスト。
    required: true
  source-repository:
    description: ソース元のリポジトリ。
    required: true
  delete:
    description: 既存のラベルを削除するかどうか。
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    - name: Copy GitHub labels
      shell: pwsh
      env:
        REPOSITORIES: ${{ inputs.repositories }}
        SOURCE_REPOSITORY: ${{ inputs.source-repository }}
        DELETE: ${{ inputs.delete }}
      run: |
        $parameters = @{ 
          Repositories = $Env:REPOSITORIES
          SourceRepository = $Env:SOURCE_REPOSITORY
          Delete = [bool]::Parse($Env:DELETE)
        }
        ${{ github.action_path }}/CopyGitHubLabels.ps1 @parameters -Verbose -ErrorAction Stop
