name: Run MSBuild target
description: MSBuildターゲットを実行するアクションです。

inputs:
  dotnet-version:
    description: インストールする.NET SDKバージョン。
    required: false
    default: 10.0.100-rc.1.25451.107
  target:
    description: MSBuildターゲット名。
    required: true

outputs:
  lines:
    description: MSBuildターゲット実行時に出力された文字列。
    value: ${{ steps.x.outputs.lines }}

runs:
  using: composite
  steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@d4c94342e560b34958eacfc5d055d21461ed1c5d # v5.0.0
      with:
        dotnet-version: ${{ inputs.dotnet-version }}

    - name: Run MSBuild target
      id: x
      shell: pwsh
      run: |
        ${{ github.action_path }}/RunMSBuildTarget.ps1 `
            -Target '${{ inputs.target }}' `
            -Verbose `
            -ErrorAction Stop
