name: Run MSBuild target
description: MSBuildターゲットを実行するアクションです。

inputs:
  target:
    description: MSBuildターゲット名。
    required: true

outputs:
  lines:
    description: MSBuildターゲット実行時に出力された文字列。
    value: ${{ steps.x.outputs.lines }}

runs:
  using: composite
  steps:
    - name: Run MSBuild target
      id: x
      shell: pwsh
      run: |
        ${{ github.action_path }}/RunMSBuildTarget.ps1 `
            -Target '${{ inputs.target }}' `
            -Verbose `
            -ErrorAction Stop
