name: Run MSBuild target
description: MSBuildターゲットを実行するアクションです。

inputs:
  dotnet-version:
    description: インストールする.NET SDKバージョン。
    required: false
    default: 11.0.100-preview.3.26207.106
  target:
    description: MSBuildターゲット名。
    required: true

outputs:
  lines:
    description: MSBuildターゲット実行時に出力された文字列。
    value: ${{ steps.x.outputs.lines }}

runs:
  using: composite
  steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@c2fa09f4bde5ebb9d1777cf28262a3eb3db3ced7 # v5.2.0
      with:
        dotnet-version: ${{ inputs.dotnet-version }}

    - name: Run MSBuild target
      id: x
      shell: pwsh
      env:
        TARGET: ${{ inputs.target }}
      run: |
        $parameters = @{
          Target = $Env:TARGET
        }
        ${{ github.action_path }}/RunMSBuildTarget.ps1 @parameters -Verbose -ErrorAction Stop
