name: Run MSBuild target
description: MSBuildターゲットを実行するGitHub Actionです。

inputs:
  target:
    description: MSBuildターゲット名。
    required: true

runs:
  using: composite
  steps:
    - name: Run MSBuild target
      shell: pwsh
      run: |
        ${{ github.action_path }}/RunMSBuildTarget.ps1 `
            -Target '${{ inputs.target }}' `
            -Verbose `
            -ErrorAction Stop
