name: Create pull request
description: プルリクエストを作成するアクションです。

inputs:
  path:
    description: リポジトリのパス。
    required: false
    type: string
    default: ${{ github.workspace }}
  commit-message:
    description: コミットメッセージ。
    required: true
    type: string
  branch:
    description: ブランチ名。
    required: false
    type: string
    default: create-pull-request
  labels:
    description: ラベルのリスト。
    required: false
    type: string
    default: null

runs:
  using: composite
  steps:
    - name: Create pull request
      shell: pwsh
      working-directory: ${{ inputs.path }}
      run: |
        ${{ github.action_path }}/CreatePullRequest.ps1 `
            -CommitMessage '${{ inputs.commit-message }}' `
            -Branch '${{ inputs.branch }}' `
            -Labels '${{ inputs.labels }}' `
            -Verbose `
            -ErrorAction Stop
