name: Create pull request
description: プルリクエストを作成するアクションです。

inputs:
  path:
    description: リポジトリのパス。
    required: false
    default: ${{ github.workspace }}
  commit-message:
    description: コミットメッセージ。
    required: true
  branch:
    description: ブランチ名。
    required: false
    default: create-pull-request
  labels:
    description: ラベルのリスト。
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Create pull request
      shell: pwsh
      working-directory: ${{ inputs.path }}
      env:
        COMMIT_MESSAGE: ${{ inputs.commit-message }}
        BRANCH: ${{ inputs.branch }}
        LABELS: ${{ inputs.labels }}
      run: |
        $parameters = @{
          CommitMessage = $Env:COMMIT_MESSAGE
          Branch = $Env:BRANCH
          Labels = $Env:LABELS
        }
        ${{ github.action_path }}/CreatePullRequest.ps1 @parameters -Verbose -ErrorAction Stop
