name: Create pull request
description: プルリクエストを作成するGitHub Actionです。

inputs:
  path:
    description: リポジトリのパス。
    required: false
    default: ${{ github.workspace }}
  commit-message:
    description: コミットメッセージ。
    required: true
  title:
    description: プルリクエストのタイトル。
    required: false
    default: ''
  body:
    description: プルリクエストの本文。
    required: false
    default: null
  branch:
    description: ブランチ名。
    required: false
    default: create-pull-request/
  labels:
    description: ラベルのリスト。
    required: false
    default: null

runs:
  using: composite
  steps:
    - name: Git diff
      shell: pwsh
      id: diff
      continue-on-error: true
      run: |
        cd '${{ inputs.path }}'
        git add -N .
        git diff --name-only --exit-code

    - name: Create pull request
      if: steps.diff.outcome == 'failure'
      shell: pwsh
      run: |
        ${{ github.action_path }}/CreatePullRequest.ps1 `
            -CommitMessage '${{ inputs.commit-message }}' `
            -Title '${{ inputs.title }}' `
            -Body '${{ inputs.body }}' `
            -Branch '${{ inputs.branch }}' `
            -Labels '${{ inputs.labels }}'
