name: .NET Pack
description: dotnet packコマンドを実行するGitHub Actionです。

inputs:
  dotnet-version:
    description: インストールする.NET SDKバージョン。
    required: false
    type: string
    default: '7.0'
  configuration:
    description: ReleaseまたはDebug。
    required: false
    type: choice
    options:
      - Release
      - Debug
    default: Release
  version:
    description: バージョンを表す文字列。
    required: true
    type: string
  output-directory:
    description: 出力先ディレクトリ。
    required: false
    type: string
    default: publish

outputs:
  success:
    description: nupkgファイルの生成に成功したかどうか。
    value: ${{ steps.check-extension.outputs.nuget }}

runs:
  using: composite
  steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ inputs.dotnet-version }}.x

    - name: Pack
      shell: pwsh
      env:
        DOTNET_NOLOGO: true
        DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
        DOTNET_CLI_TELEMETRY_OPTOUT: true
      run: |
        dotnet pack `
            --configuration ${{ inputs.configuration }} `
            --output ${{ inputs.output-directory }} `
            -p:Version=${{ inputs.version }}

    - name: Check extension
      id: check-extension
      uses: finphie/Actions/.github/actions/check-extension@main
      with:
        path: ${{ inputs.output-directory }}
