name: .NET Pack
description: dotnet packコマンドを実行するアクションです。

inputs:
  dotnet-version:
    description: インストールする.NET SDKバージョン。
    required: false
    default: 9.0.100-rc.2.24474.11
  configuration:
    description: ビルド構成。
    required: false
    default: Release
  version:
    description: バージョンを表す文字列。
    required: true
  output-directory:
    description: 出力先ディレクトリ。
    required: false
    default: pack

outputs:
  success:
    description: nupkgファイルの生成に成功したかどうか。
    value: ${{ steps.check-extension.outputs.nuget }}

runs:
  using: composite
  steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@3e891b0cb619bf60e2c25674b222b8940e2c1c25 # v4.1.0
      with:
        dotnet-version: ${{ inputs.dotnet-version }}

    - name: Pack
      shell: pwsh
      env:
        DOTNET_NOLOGO: true
        DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
        DOTNET_CLI_TELEMETRY_OPTOUT: true
      run: |
        dotnet pack `
            --configuration '${{ inputs.configuration }}' `
            --output '${{ inputs.output-directory }}' `
            -p:Version=${{ inputs.version }}

    - name: Check extension
      id: check-extension
      uses: finphie/Actions/.github/actions/check-extension@main
      with:
        path: ${{ inputs.output-directory }}
