name: Upload release assets
description: リリースにファイルをアップロードするアクションです。

inputs:
  tag:
    description: 対象のgitタグ。
    required: true
    type: string
  files:
    description: アップロード対象のファイルリスト。
    required: true
    type: string

runs:
  using: composite
  steps:
    - name: Upload release assets
      shell: pwsh
      run: |
        ${{ github.action_path }}/UploadReleaseAssets.ps1 `
            -Tag '${{ inputs.tag }}' `
            -Files '${{ inputs.files }}' `
            -Verbose `
            -ErrorAction Stop
