name: Upload release assets
description: リリースにファイルをアップロードするアクションです。

inputs:
  tag:
    description: 対象のgitタグ。
    required: true
  files:
    description: アップロード対象のファイルリスト。
    required: true

runs:
  using: composite
  steps:
    - name: Upload release assets
      shell: pwsh
      env:
        TAG: ${{ inputs.tag }}
        FILES: ${{ inputs.files }}
      run: |
        $parameters = @{
          Tag = $Env:TAG
          Files = $Env:FILES
        }
        ${{ github.action_path }}/UploadReleaseAssets.ps1 @parameters -Verbose -ErrorAction Stop
