name: Build(YAML)

on:
  workflow_call:
  pull_request:
    paths:
      - '**/*.yml'

permissions: {}

jobs:
  main:
    name: Main
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

      - name: Install yamllint
        run: pip install yamllint

      - name: Lint YAML
        run: yamllint .
