name: Build(.NET)

on:
  workflow_call:
    inputs:
      dotnet-version:
        description: インストールする.NET SDKバージョン。
        required: false
        type: string
        default: 10.0.100-rc.1.25451.107
      configuration:
        description: ビルド構成。
        required: false
        type: string
        default: Release

permissions: {}

env:
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  main:
    name: Main
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    permissions: {}

    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
          - windows-11-arm
          - ubuntu-latest
          - ubuntu-24.04-arm
          - macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Check
        id: check
        uses: finphie/Actions/.github/actions/check-extension@main

      - name: Setup .NET
        if: steps.check.outputs.dotnet == 'true'
        uses: actions/setup-dotnet@d4c94342e560b34958eacfc5d055d21461ed1c5d # v5.0.0
        with:
          dotnet-version: ${{ inputs.dotnet-version }}

      - name: .NET Build
        if: steps.check.outputs.dotnet == 'true'
        run: dotnet build --configuration ${{ inputs.configuration }} -warnAsError

      - name: .NET Test
        if: steps.check.outputs.dotnet == 'true'
        shell: pwsh
        run: |
          dotnet test --configuration ${{ inputs.configuration }} --no-build
          if ($LastExitCode -eq 8) { exit 0 }
