name: Build(.NET)

on:
  workflow_call:
    inputs:
      dotnet-version:
        description: インストールする.NET SDKバージョン。
        required: false
        type: string
        default: 9.0.100-rc.2.24474.11
      configuration:
        description: ビルド構成。
        required: false
        type: string
        default: Release

permissions: {}

env:
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  main:
    name: Main
    runs-on: windows-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

      - name: Check
        id: check
        uses: finphie/Actions/.github/actions/check-extension@main

      - name: Setup .NET
        if: steps.check.outputs.dotnet == 'true'
        uses: actions/setup-dotnet@6bd8b7f7774af54e05809fcc5431931b3eb1ddee # v4.0.1
        with:
          dotnet-version: ${{ inputs.dotnet-version }}

      - name: .NET Build
        if: steps.check.outputs.dotnet == 'true'
        run: dotnet build --configuration ${{ inputs.configuration }} -warnAsError

      - name: .NET Test
        if: steps.check.outputs.dotnet == 'true'
        run: dotnet test --configuration ${{ inputs.configuration }} --no-build
