name: Build(.NET)

on:
  workflow_call:
    inputs:
      dotnet-version:
        required: false
        type: string
        default: 7.0.x
      configuration:
        required: false
        type: string
        default: Release

permissions:
  contents: read

env:
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  main:
    name: Test
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ inputs.dotnet-version }}

      - name: .NET Build
        run: dotnet build --configuration ${{ inputs.configuration }} -warnAsError

      - name: .NET Test
        run: dotnet test --configuration ${{ inputs.configuration }} --no-build
