name: Build(.NET)

on:
  workflow_call:
    inputs:
      dotnet-version:
        description: インストールする.NET SDKバージョン。
        required: false
        type: string
        default: 11.0.100-preview.3.26207.106
      configuration:
        description: ビルド構成。
        required: false
        type: string
        default: Release

permissions: {}

env:
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  main:
    name: Main
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    permissions: {}

    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
          - windows-11-arm
          - ubuntu-latest
          - ubuntu-24.04-arm
          - macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Setup .NET
        uses: actions/setup-dotnet@9a946fdbd5fb07b82b2f5a4466058b876ab72bb2 # v5.3.0
        with:
          dotnet-version: ${{ inputs.dotnet-version }}

      - name: .NET Build
        run: dotnet build --configuration ${{ inputs.configuration }} -warnAsError

      - name: .NET Test
        shell: pwsh
        run: |
          dotnet test --configuration ${{ inputs.configuration }} --no-build
          if ($LastExitCode -eq 8) { exit 0 }
