name: Build(Markdown)

on:
  workflow_call:
  pull_request:
    paths:
      - '**/*.md'
      - .markdownlint.yml
      - .github/workflows/build-markdown.yml

permissions: {}

jobs:
  main:
    name: Main
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Install markdownlint-cli
        run: sudo npm install -g markdownlint-cli

      - name: Lint markdown
        run: markdownlint '**/*.md'
