name: Build(Python)

on:
  workflow_call:

permissions: {}

jobs:
  main:
    name: Main
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install flake8
        run: pip install flake8

      - name: Install Pyright
        run: sudo npm install -g pyright

      - name: Lint Python (flake8)
        run: flake8

      - name: Lint Python (pyright)
        run: pyright
