name: Build(YAML)

on:
  workflow_call:
  pull_request:
    paths:
      - '**/*.yml'
      - .github/workflows/build-yaml.yml

permissions: {}

jobs:
  main:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install yamllint
        run: pip install yamllint

      - name: Lint YAML
        run: yamllint .
