name: Build(PowerShell)

on:
  workflow_call:
  pull_request:
    paths:
      - '**/*.ps1'
      - '**/*.psd1'
      - '**/*.psm1'
      - .github/workflows/build-powershell.yml

permissions: {}

defaults:
  run:
    shell: pwsh

jobs:
  main:
    name: Main
    runs-on: ubuntu-latest
    timeout-minutes: 10

    permissions: {}

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install PSScriptAnalyzer
        run: Install-Module -Name PSScriptAnalyzer -Force

      - name: Lint PowerShell
        run: Invoke-ScriptAnalyzer -Path . -EnableExit -Recurse
