name: Build(PowerShell)

on:
  workflow_call:
  pull_request:
    paths:
      - '**/*.ps1'
      - '**/*.psd1'
      - '**/*.psm1'
      - .github/workflows/build-powershell.yml

permissions: {}

defaults:
  run:
    shell: pwsh

jobs:
  main:
    name: Main
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

      - name: Install PSScriptAnalyzer
        run: Install-Module -Name PSScriptAnalyzer -Force

      - name: Lint PowerShell
        run: Invoke-ScriptAnalyzer -Path . -EnableExit -Recurse
