name: Build(YAML)

on:
  workflow_call:
  pull_request:
    paths:
      - '**/*.yml'

permissions: {}

jobs:
  main:
    name: Main
    runs-on: ubuntu-latest
    timeout-minutes: 10

    permissions: {}

    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Install yamllint
        run: pip install yamllint

      - name: Lint YAML
        run: yamllint .
