name: Check .NET platform

on:
  workflow_call:
    inputs:
      settings-file-path:
        description: 設定ファイルのパス。
        required: false
        type: string
        default: null
    outputs:
      projects:
        description: upload-artifacts-dotnet.ymlワークフローの引数となるJSON文字列を出力する。
        value: ${{ jobs.main.outputs.projects }}

permissions: {}

jobs:
  main:
    name: Main
    runs-on: ubuntu-latest
    timeout-minutes: 10

    outputs:
      projects: ${{ steps.get-dotnet-projects.outputs.projects }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

      - name: Get ProjectIdentifier
        id: project-identifier
        uses: finphie/Actions/.github/actions/run-msbuild-target@main
        with:
          target: GetProjectIdentifier

      - name: Get .NET projects
        id: get-dotnet-projects
        uses: finphie/Actions/.github/actions/get-dotnet-projects@main
        with:
          projects: ${{ steps.project-identifier.outputs.lines }}
          settings-file-path: ${{ inputs.settings-file-path }}
