name: Deploy(.NET)

on:
  workflow_call:
    inputs:
      version:
        description: バージョンを表す文字列。
        required: true
        type: string
      release:
        description: 安定版リリースかどうか。
        required: true
        type: boolean
      suffix:
        description: アップロードする成果物名の末尾に追加する文字列。
        required: true
        type: string
    secrets:
      AZURE_ARTIFACT_PAT:
        description: 「Packaging」スコープの読み書きを許可したAzure DevOps Personal Access Token。
        required: true
      NUGET_API_KEY:
        description: 「Push」スコープを許可したNuGet APIキー。
        required: true

permissions: {}

jobs:
  check:
    name: Check
    uses: finphie/Actions/.github/workflows/check-dotnet-platform.yml@main

  pack:
    name: Push(NuGet)
    uses: finphie/Actions/.github/workflows/upload-nuget-library.yml@main
    with:
      version: ${{ inputs.version }}
      release: ${{ inputs.release }}
    secrets:
      AZURE_ARTIFACT_PAT: ${{ secrets.AZURE_ARTIFACT_PAT }}
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}

  publish-console:
    name: Publish(Console)
    needs: check
    if: needs.check.outputs.console != ''

    strategy:
      fail-fast: false
      matrix:
        project: ${{ fromJson(needs.check.outputs.console) }}
        architecture: ['x64', 'arm64']

    uses: finphie/Actions/.github/workflows/upload-artifacts-dotnet.yml@main
    with:
      project: ${{ matrix.project }}
      platform: windows
      architecture: ${{ matrix.architecture }}
      version: ${{ inputs.version }}
      suffix: ${{ inputs.suffix }}

  publish-windows:
    name: Publish(Windows)
    needs: check
    if: needs.check.outputs.windows != ''

    strategy:
      fail-fast: false
      matrix:
        project: ${{ fromJson(needs.check.outputs.windows) }}
        architecture: ['x64', 'arm64']

    uses: finphie/Actions/.github/workflows/upload-artifacts-dotnet.yml@main
    with:
      project: ${{ matrix.project }}
      platform: windows
      architecture: ${{ matrix.architecture }}
      version: ${{ inputs.version }}
      suffix: ${{ inputs.suffix }}

  publish-android:
    name: Publish(Android)
    needs: check
    if: needs.check.outputs.android != ''

    strategy:
      fail-fast: false
      matrix:
        project: ${{ fromJson(needs.check.outputs.android) }}

    uses: finphie/Actions/.github/workflows/upload-artifacts-dotnet.yml@main
    with:
      project: ${{ matrix.project }}
      platform: android
      architecture: arm64
      version: ${{ inputs.version }}
      suffix: ${{ inputs.suffix }}

  publish-server:
    name: Publish(Server)
    needs: check
    if: needs.check.outputs.server != ''

    strategy:
      fail-fast: false
      matrix:
        project: ${{ fromJson(needs.check.outputs.server) }}
        architecture: ['x64', 'arm64']

    uses: finphie/Actions/.github/workflows/upload-artifacts-dotnet.yml@main
    with:
      project: ${{ matrix.project }}
      platform: server
      architecture: ${{ matrix.architecture }}
      version: ${{ inputs.version }}
      suffix: ${{ inputs.suffix }}

  publish-browser:
    name: Publish(Browser)
    needs: check
    if: needs.check.outputs.browser != ''

    strategy:
      fail-fast: false
      matrix:
        project: ${{ fromJson(needs.check.outputs.browser) }}

    uses: finphie/Actions/.github/workflows/upload-artifacts-dotnet.yml@main
    with:
      project: ${{ matrix.project }}
      platform: browser
      architecture: wasm
      version: ${{ inputs.version }}
      suffix: ${{ inputs.suffix }}
