name: Deploy(Docker)

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      version-major:
        required: true
        type: string

permissions:
  packages: write

jobs:
  main:
    name: Main
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get repository name
        id: get
        uses: finphie/Actions/.github/actions/pascal-to-kebab@main
        with:
          text: ${{ github.event.repository.name }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          build-args: VERSION=${{ inputs.version }}
          tags: |
            ghcr.io/${{ github.actor }}/${{ steps.get.outputs.text }}:v${{ inputs.version }}
            ghcr.io/${{ github.actor }}/${{ steps.get.outputs.text }}:v${{ inputs.version-major }}
