name: Deploy(Docker)

on:
  workflow_call:
    inputs:
      version:
        description: バージョンを表す文字列。
        required: true
        type: string
      version-major:
        description: メジャーバージョンを表す数値。
        required: true
        type: string

permissions:
  packages: write

jobs:
  main:
    name: Main
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get repository name
        id: get
        uses: finphie/Actions/.github/actions/pascal-to-kebab@main
        with:
          text: ${{ github.event.repository.name }}

      - name: Build and push
        uses: docker/build-push-action@4f58ea79222b3b9dc2c8bbdd6debcef730109a75 # v6.9.0
        with:
          push: true
          build-args: VERSION=${{ inputs.version }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ steps.get.outputs.text }}:v${{ inputs.version }}
            ghcr.io/${{ github.repository_owner }}/${{ steps.get.outputs.text }}:v${{ inputs.version-major }}
