name: Deploy(Docker)

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      version-major:
        required: true
        type: string
    secrets:
      GITHUB_TOKEN:
        required: true
  pull_request:

permissions:
  contents: read

jobs:
  main:
    name: Main
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get repository name
        id: get
        uses: finphie/Actions/.github/actions/pascal-to-kebab@20221230
        with:
          text: GitHubSettingsSync
