name: Normalize line endings

on:
  workflow_call:

permissions:
  contents: write

jobs:
  main:
    name: Main
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ github.event.pull_request.head.ref || github.ref }}

      - name: Normalize line endings
        uses: finphie/Actions/.github/actions/git-push@main
        with:
          commit-message: Normalize line endings
