name: Normalize line endings

on:
  workflow_call:

permissions: {}

jobs:
  main:
    name: Main
    runs-on: ubuntu-latest
    timeout-minutes: 10

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          ref: ${{ github.event.pull_request.head.ref || github.ref }}

      - name: Normalize line endings
        uses: finphie/Actions/.github/actions/git-push@main
        with:
          commit-message: Normalize line endings
