name: Normalize line endings

on:
  workflow_call:

permissions: {}

jobs:
  main:
    name: Main
    runs-on: ubuntu-latest
    timeout-minutes: 10

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          ref: ${{ github.event.pull_request.head.ref || github.ref }}

      - name: Normalize line endings
        uses: finphie/Actions/.github/actions/git-push@main
        with:
          commit-message: Normalize line endings
