name: Release

on:
  workflow_call:
    inputs:
      version:
        description: バージョンを表す文字列。
        required: true
        type: string
      tag:
        description: gitタグ名。
        required: true
        type: string

permissions:
  contents: write
  id-token: write
  attestations: write

jobs:
  main:
    name: Main
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Download artifacts
        id: download-artifact
        uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
        with:
          path: ${{ runner.temp }}

      - name: Check extension
        id: check-extension
        uses: finphie/Actions/.github/actions/check-extension@main
        with:
          path: ${{ steps.download-artifact.outputs.download-path }}
          recurse: true

      - name: Generate artifact attestation
        if: steps.check-extension.outputs.zip == 'true' || steps.check-extension.outputs.exe == 'true'
        uses: actions/attest-build-provenance@977bb373ede98d70efdf65b84cb5f73e068dcc2a # v3.0.0
        with:
          subject-path: |
            ${{ steps.download-artifact.outputs.download-path }}/**/*.zip
            ${{ steps.download-artifact.outputs.download-path }}/**/*.tar.gz
            ${{ steps.download-artifact.outputs.download-path }}/**/*.exe

      - name: Create release
        uses: finphie/Actions/.github/actions/create-release@main
        with:
          title: Version ${{ inputs.version }}
          tag: ${{ inputs.tag }}
          files: |
            ${{ steps.download-artifact.outputs.download-path }}/**/*.zip
            ${{ steps.download-artifact.outputs.download-path }}/**/*.tar.gz
            ${{ steps.download-artifact.outputs.download-path }}/**/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
