name: Release

on:
  workflow_call:
    inputs:
      version:
        description: バージョンを表す文字列。
        required: true
        type: string
      tag:
        description: gitタグ名。
        required: true
        type: string

permissions:
  contents: write
  id-token: write
  attestations: write

jobs:
  main:
    name: Main
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Create release notes
        uses: release-drafter/release-drafter@b1476f6e6eb133afa41ed8589daba6dc69b4d3f5 # v6.1.0
        with:
          publish: true
          prerelease: false
          name: Version ${{ inputs.version }}
          tag: ${{ inputs.tag }}
          version: ${{ inputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Download artifacts
        id: download-artifact
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          path: ${{ runner.temp }}

      - name: Check extension
        id: check-extension
        uses: finphie/Actions/.github/actions/check-extension@main
        with:
          path: ${{ steps.download-artifact.outputs.download-path }}
          recurse: true

      - name: Generate artifact attestation
        if: steps.check-extension.outputs.zip == 'true' || steps.check-extension.outputs.exe == 'true'
        uses: actions/attest-build-provenance@c074443f1aee8d4aeeae555aebba3282517141b2 # v2.2.3
        with:
          subject-path: |
            ${{ runner.temp }}/**/*.zip
            ${{ runner.temp }}/**/*.tar.gz
            ${{ runner.temp }}/**/*.exe

      - name: Upload release assets
        if: steps.check-extension.outputs.zip == 'true' || steps.check-extension.outputs.exe == 'true'
        uses: finphie/Actions/.github/actions/upload-release-assets@main
        with:
          tag: ${{ inputs.tag }}
          files: |
            ${{ runner.temp }}/**/*.zip
            ${{ runner.temp }}/**/*.tar.gz
            ${{ runner.temp }}/**/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
