name: Sync(labels)

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 */3 * *

permissions: {}

jobs:
  main:
    name: Main
    runs-on: ubuntu-latest
    timeout-minutes: 10

    permissions: {}

    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Get repositories
        id: get
        uses: ./.github/actions/get-github-repositories
        with:
          source: true
          no-archived: true
          visibility: public
          exclude: ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create token
        id: app-token
        uses: actions/create-github-app-token@67018539274d69449ef7c02e8e71183d1719ab42 # v2.1.4
        with:
          app-id: ${{ vars.LABELS_SYNC_APP_ID }}
          private-key: ${{ secrets.LABELS_SYNC_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Sync labels
        uses: ./.github/actions/copy-github-labels
        with:
          repositories: ${{ steps.get.outputs.repositories }}
          source-repository: ${{ github.repository }}
          delete: true
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
