name: Sync(secrets)

on:
  workflow_dispatch:
  pull_request:

permissions: {}

jobs:
  secrets:
    name: Main
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get repositories
        uses: ./.github/actions/get-github-repositories
        id: get
        with:
          language: C#
          no-archived: true
          source: true
          exclude: |
            ${{ github.repository }}
            finphie/Benchmarks
        env:
          GITHUB_TOKEN: ${{ secrets.SYNC_GITHUB_SETTINGS_PAT }}

      - name: Sync dotnet secrets
        uses: google/secrets-sync-action@v1.7.0
        with:
          dry_run: true
          repositories: ${{ steps.get.outputs.repositories }}
          secrets: |
            AZURE_ARTIFACT_PAT
            NUGET_API_KEY
          repositories_list_regex: false
          GITHUB_TOKEN: ${{ secrets.SYNC_GITHUB_SETTINGS_PAT }}
        env:
          AZURE_ARTIFACT_PAT: ${{ secrets.AZURE_ARTIFACT_PAT }}
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
