name: Sync(dotfiles)

on:
  workflow_dispatch:
    inputs:
      repository:
        description: リポジトリ名
        required: false
        type: string
        default: All

permissions: {}

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    timeout-minutes: 10

    outputs:
      repositories: ${{ github.event.inputs.repository == 'All' && steps.get.outputs.repositories || format('["{0}/{1}"]', github.repository_owner, github.event.inputs.repository) }}

    steps:
      - name: Checkout repository
        if: github.event.inputs.repository == 'All'
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Get repositories
        if: github.event.inputs.repository == 'All'
        uses: ./.github/actions/get-github-repositories
        id: get
        with:
          source: true
          no-archived: true
          visibility: public
          language: C#
          exclude: |
            ${{ github.repository }}
            finphie/dotfiles
          json: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  main:
    name: Main
    needs: check
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      max-parallel: 3
      fail-fast: false
      matrix:
        repository: ${{ fromJSON(needs.check.outputs.repositories) }}

    env:
      SOURCE_REPOSITORY: ${{ github.repository_owner }}/dotfiles
      TARGET_REPOSITORY: ${{ matrix.repository }}
      SOURCE_REPOSITORY_PATH: __source_repository__
      TARGET_REPOSITORY_PATH: __target_repository__

    steps:
      - name: Checkout ${{ env.SOURCE_REPOSITORY }} repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          repository: ${{ env.SOURCE_REPOSITORY }}
          path: ${{ env.SOURCE_REPOSITORY_PATH }}
          fetch-depth: 0

      - name: Get target repository name
        id: get-repository-name
        uses: finphie/Actions/.github/actions/get-repository-name@main
        with:
          repository: ${{ env.TARGET_REPOSITORY }}

      - name: Create token
        uses: actions/create-github-app-token@0f859bf9e69e887678d5bbfbee594437cb440ffe # v2.1.0
        id: app-token
        with:
          app-id: ${{ vars.REPOSITORY_SYNC_APP_ID }}
          private-key: ${{ secrets.REPOSITORY_SYNC_PRIVATE_KEY }}
          repositories: |
            ${{ steps.get-repository-name.outputs.repository-name }}

      - name: Checkout ${{ env.TARGET_REPOSITORY }} repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          repository: ${{ env.TARGET_REPOSITORY }}
          path: ${{ env.TARGET_REPOSITORY_PATH }}
          token: ${{ steps.app-token.outputs.token }}

      - name: Sync repositories
        uses: finphie/Actions/.github/actions/sync-repositories@main
        with:
          source-path: ${{ env.SOURCE_REPOSITORY_PATH }}
          target-path: ${{ env.TARGET_REPOSITORY_PATH }}
          settings-file-path: .github/dotfiles.json
          commit-message: Update dotfiles
          branch: chore
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
