name: Sync(secrets)

on:
  workflow_dispatch:
  pull_request:

permissions: {}

jobs:
  secrets:
    name: Main
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - run: ls
      - run: ls Source
      - run: ls .github

      - name: Get repositories
        uses: ./.github/actions/get-github-repositories
        id: get
        with:
          no-archived: true
          source: true
          visibility: public
          exclude: ${{ github.repository }}

      - name: Get repositories
        uses: finphie/Actions/.github/actions/get-github-repositories@main
        id: get2
        if: always()
        with:
          no-archived: true
          source: true
          visibility: public
          exclude: ${{ github.repository }}

      - name: Sync secrets
        uses: google/secrets-sync-action@v1.7.0
        with:
          dry_run: true
          repositories: ${{ steps.get.outputs.repositories }}
          secrets: |
            AZURE_ARTIFACT_PAT
            NUGET_API_KEY
          repositories_list_regex: false
          GITHUB_TOKEN: ${{ secrets.SYNC_GITHUB_SETTINGS_PAT }}
        env:
          AZURE_ARTIFACT_PAT: ${{ secrets.AZURE_ARTIFACT_PAT }}
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
