name: Sync(labels)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 */3 * *'

permissions: {}

jobs:
  main:
    name: Main
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

      - name: Get repositories
        uses: ./.github/actions/get-github-repositories
        id: get
        with:
          no-archived: true
          source: true
          exclude: ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_PUBLIC_REPOSITORY_PAT }}

      - name: Sync labels
        uses: ./.github/actions/copy-github-labels
        with:
          repositories: ${{ steps.get.outputs.repositories }}
          source-repository: ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_PUBLIC_REPOSITORY_PAT }}
