name: Sync(dotfiles)

on:
  workflow_dispatch:

permissions: {}

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest

    outputs:
      repositories: ${{ steps.get.outputs.repositories }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get repositories
        uses: ./.github/actions/get-github-repositories
        id: get
        with:
          no-archived: true
          source: true
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_PUBLIC_REPOSITORY_PAT }}

  main:
    name: Main
    needs: check
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 3
      fail-fast: false
      matrix:
        repository: ${{ needs.check.outputs.repositories }}

    env:
      SOURCE_REPOSITORY: ${{ github.actor }}/dotfiles
      TARGET_REPOSITORY: ${{ matrix.repository }}
      SOURCE_REPOSITORY_PATH: __source_repository__
      TARGET_REPOSITORY_PATH: __target_repository__

    steps:
      - name: Checkout ${{ env.SOURCE_REPOSITORY }} repository
        uses: actions/checkout@v3
        with:
          repository: ${{ env.SOURCE_REPOSITORY }}
          path: ${{ env.SOURCE_REPOSITORY_PATH }}
          fetch-depth: 0

      - name: Checkout ${{ env.TARGET_REPOSITORY }} repository
        uses: actions/checkout@v3
        with:
          repository: ${{ env.TARGET_REPOSITORY }}
          path: ${{ env.TARGET_REPOSITORY_PATH }}
          token: ${{ secrets.ACTIONS_SYNC_DOTFILES_PAT }}

      - name: Sync repositories
        uses: finphie/Actions/.github/actions/sync-repositories@main
        with:
          source-path: ${{ env.SOURCE_REPOSITORY_PATH }}
          target-path: ${{ env.TARGET_REPOSITORY_PATH }}
          settings-file-path: .github/dotfiles.json
          commit-message: Update dotfiles
          branch: chore
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_SYNC_DOTFILES_PAT }}
