name: Sync(secrets)

on:
  workflow_dispatch:

permissions: {}

jobs:
  main:
    name: Main
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Get repositories
        uses: ./.github/actions/get-github-repositories
        id: get
        with:
          source: true
          no-archived: true
          language: C#
          exclude: |
            ${{ github.repository }}
            finphie/Performance
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_PUBLIC_REPOSITORY_PAT }}

      - name: Sync dotnet secrets
        uses: google/secrets-sync-action@v1.7.1
        with:
          repositories: ${{ steps.get.outputs.repositories }}
          secrets: |
            AZURE_ARTIFACT_PAT
            NUGET_API_KEY
          repositories_list_regex: false
          GITHUB_TOKEN: ${{ secrets.ACTIONS_PUBLIC_REPOSITORY_PAT }}
        env:
          AZURE_ARTIFACT_PAT: ${{ secrets.AZURE_ARTIFACT_PAT }}
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
