name: Sync(labels)

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 */3 * *

permissions: {}

jobs:
  main:
    name: Main
    runs-on: ubuntu-latest
    timeout-minutes: 10

    permissions: {}

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Get repositories
        id: get
        uses: ./.github/actions/get-github-repositories
        with:
          source: true
          no-archived: true
          visibility: public
          exclude: ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create token
        id: app-token
        uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3 # v3.1.1
        with:
          client-id: ${{ vars.LABELS_SYNC_APP_ID }}
          private-key: ${{ secrets.LABELS_SYNC_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Sync labels
        uses: ./.github/actions/copy-github-labels
        with:
          repositories: ${{ steps.get.outputs.repositories }}
          source-repository: ${{ github.repository }}
          delete: true
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
