name: Sync

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 */3 * *'

jobs:
  labels:
    name: 'Sync: labels'
    runs-on: ubuntu-latest

    steps:
      - name: Sync labels
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_SYNC_PAT }}
        run: |
          $repositories = gh repo list --source --no-archived --visibility=public --limit 1000 --json name --jq '.[].name'
          $actor = '${{ github.actor }}'
          $currentRepository = '${{ github.event.repository.name }}'

          gh label list

          foreach ($repository in $repositories) {
            if ($repository -eq $currentRepository) {
              continue
            }

            gh label clone $actor/$currentRepository --force --repo $actor/$repository
          }
