name: Sync(labels)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 */3 * *'

permissions: {}

jobs:
  main:
    name: Main
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Get repositories
        uses: ./.github/actions/get-github-repositories
        id: get
        with:
          source: true
          no-archived: true
          visibility: public
          exclude: ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create token
        uses: actions/create-github-app-token@af35edadc00be37caa72ed9f3e6d5f7801bfdf09 # v1.11.7
        id: app-token
        with:
          app-id: ${{ vars.LABELS_SYNC_APP_ID }}
          private-key: ${{ secrets.LABELS_SYNC_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Sync labels
        uses: ./.github/actions/copy-github-labels
        with:
          repositories: ${{ steps.get.outputs.repositories }}
          source-repository: ${{ github.repository }}
          delete: true
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
