name: Sync(labels)

on:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 0 */3 * *'

permissions: {}

jobs:
  labels:
    name: Main
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get repositories
        uses: ./.github/actions/get-github-repositories
        id: get
        with:
          no-archived: true
          source: true
          exclude: ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.SYNC_GITHUB_SETTINGS_PAT }}

      - name: Sync labels
        uses: ./.github/actions/copy-github-labels
        with:
          repositories: ${{ steps.get.outputs.repositories }}
          source-repository: ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.SYNC_GITHUB_SETTINGS_PAT }}
