name: Sync(labels)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 */3 * *'

permissions: {}

jobs:
  labels:
    name: Main
    runs-on: ubuntu-latest

    steps:
      - name: Sync labels
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ secrets.SYNC_GITHUB_SETTINGS_PAT }}
        run: |
          $repositories = gh repo list --source --no-archived --visibility=public --limit 1000 --json name --jq '.[].name'
          $actor = '${{ github.actor }}'
          $currentRepository = '${{ github.event.repository.name }}'

          gh label list --repo $actor/$currentRepository

          foreach ($repository in $repositories) {
            if ($repository -eq $currentRepository) {
              continue
            }

            Write-Output $repository
            gh label clone $actor/$currentRepository --force --repo $actor/$repository
          }
