name: Sync(secrets)

on:
  workflow_dispatch:
    inputs:
      repository:
        description: リポジトリ名
        required: false
        type: string
        default: All

permissions: {}

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    timeout-minutes: 10

    outputs:
      repositories: ${{ github.event.inputs.repository == 'All' && steps.get.outputs.repositories || format('["{0}/{1}"]', github.repository_owner, github.event.inputs.repository) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Get repositories
        uses: ./.github/actions/get-github-repositories
        id: get
        with:
          source: true
          no-archived: true
          visibility: public
          language: C#
          exclude: |
            ${{ github.repository }}
            finphie/dotfiles
            finphie/Performance
          json: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  main:
    name: Main
    needs: check
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      max-parallel: 3
      fail-fast: false
      matrix:
        repository: ${{ fromJSON(needs.check.outputs.repositories) }}

    steps:
      - name: Get target repository name
        id: get-repository-name
        uses: finphie/Actions/.github/actions/get-repository-name@main
        with:
          repository: ${{ matrix.repository }}

      - name: Create token
        uses: actions/create-github-app-token@5d869da34e18e7287c1daad50e0b8ea0f506ce69 # v1.11.0
        id: app-token
        with:
          app-id: ${{ vars.SECRETS_SYNC_APP_ID }}
          private-key: ${{ secrets.SECRETS_SYNC_PRIVATE_KEY }}
          repositories: |
            ${{ steps.get-repository-name.outputs.repository-name }}

      - name: Sync dotnet secrets
        uses: finphie/GitHubSecretsSync@v0.1.2
        with:
          repository: ${{ matrix.repository }}
          secrets: |
            AZURE_ARTIFACT_PAT
            NUGET_API_KEY
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          AZURE_ARTIFACT_PAT: ${{ secrets.AZURE_ARTIFACT_PAT }}
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
