name: Sync secrets

on:
  workflow_dispatch:

permissions: {}

jobs:
  secrets:
    name: 'Sync: secrets'
    runs-on: ubuntu-latest

    steps:
      - name: Get repositories
        id: get
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ secrets.SYNC_GITHUB_SETTINGS_PAT }}
        run: |
          $repositories = gh repo list --source --no-archived --visibility=public --limit 1000 --json name --jq '.[].name'
          $actor = '${{ github.actor }}'
          $currentRepository = '${{ github.event.repository.name }}'
          $repositories = ($repositories | Where-Object { $_ -ne $currentRepository } | ForEach-Object { "$actor/$_" }) -Join '%0A'

          Write-Output "::set-output name=repositories::$repositories"

      - name: Sync secrets
        uses: google/secrets-sync-action@v1.7.0
        with:
          repositories: |
            ${{ steps.get.outputs.repositories }}
          secrets: |
            AZURE_ARTIFACT_PAT
            NUGET_API_KEY
          repositories_list_regex: false
          GITHUB_TOKEN: ${{ secrets.SYNC_GITHUB_SETTINGS_PAT }}
        env:
          AZURE_ARTIFACT_PAT: ${{ secrets.AZURE_ARTIFACT_PAT }}
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}