name: Test

on:
  pull_request:

jobs:
  test1:
    name: Main
    runs-on: ubuntu-latest
    permissions: {}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get repository name
        id: get
        uses: finphie/Actions/.github/actions/pascal-to-kebab@20221230
        with:
          text: GitHubSettingsSync Abc

      - uses: finphie/Actions/.github/actions/git-versioning@20221230
        id: versioning
        with:
          hash: ${{ github.sha }}
          revision:  ${{ github.run_number }}

      - run: |
          echo "${{ steps.versioning.outputs.version }}"
          echo "${{ steps.versioning.outputs.version-major }}"
          echo "${{ steps.versioning.outputs.release }}"

  test2:
    name: create-pull-request
    runs-on: ubuntu-latest
    permissions: {}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: finphie/Actions/.github/actions/create-pull-request@20221230
        with:
          commit-message: Test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
