name: Test

on:
  pull_request:

permissions: {}

jobs:
  test:
    name: Main
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Benchmarks repository
        uses: actions/checkout@v3
        with:
          repository: finphie/__test__20201003__
          fetch-depth: 0
          token: ${{ secrets.SYNC_DOTFILES_PAT }}

      - run: |
          echo -n > empty.txt

      - name: Create PR
        uses: finphie/Actions/.github/actions/create-pull-request@20221230
        with:
          commit-message: Test commit
        env:
          GITHUB_TOKEN: ${{ secrets.SYNC_DOTFILES_PAT }}
