name: Test

on:
  pull_request:

permissions: {}

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Update PowerShell
        working-directory: ${{ runner.temp }}
        run: |
          wget -q "https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/packages-microsoft-prod.deb"
          sudo dpkg -i packages-microsoft-prod.deb
          sudo apt-get install -y powershell

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update repository.json
        uses: finphie/Actions/.github/actions/update-repository-json@20221230
        with:
          solution-name: ${{ github.event.repository.name }}
          projects: |
            Project1,Windows
            Project2,Console

      - run: cat repository.json
