name: Test

on:
  pull_request:

jobs:
  test2:
    name: create-pull-request
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: echo -n > empty.text

      - uses: finphie/Actions/.github/actions/create-pull-request@20221230
        with:
          commit-message: Test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
