name: Test

on:
  push:

permissions: {}

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest

    outputs:
      repositories: ${{ steps.get.outputs.repositories }}
      repository: '[finphie/GitHubSettingsSync]'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get repositories
        uses: ./.github/actions/get-github-repositories
        id: get
        with:
          language: C#
          no-archived: true
          source: true
          exclude:
            ${{ github.repository }}
            finphie/dotfiles
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_PUBLIC_REPOSITORY_PAT }}

  main:
    name: Main
    needs: check
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 3
      fail-fast: false
      matrix:
        repository: ${{ needs.check.outputs.repositories != '' && fromJSON(needs.check.outputs.repositories) || fromJSON(needs.check.outputs.repository) }}

    steps:
      - run: echo '${{ matrix.repository }}'
