on:
  pull_request:

permissions:
  contents: write
  pull-requests: write

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main

      - run: touch a.txt

      - name: Create pull request
        uses: finphie/Actions/.github/actions/create-pull-request@202301282235
        with:
          path: ${{ github.workspace }}
          commit-message: Commit message
          branch: create-pull-request
          labels: null
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
