name: Test

on:
  pull_request:

jobs:
  test1:
    name: create-pull-request
    runs-on: ubuntu-latest
    permissions: {}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: finphie/__test__20201003__
          token: ${{ secrets.ACTIONS_SYNC_DOTFILES_PAT }}

      - run: echo -n > empty.text

      - uses: finphie/Actions/.github/actions/create-pull-request@20221230
        with:
          commit-message: Test
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_SYNC_DOTFILES_PAT }}

  test2:
    name: create-pull-request
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      issues: write
      repository-projects: write
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: echo -n > empty.text

      - uses: finphie/Actions/.github/actions/create-pull-request@20221230
        with:
          commit-message: Test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
