name: Test

on:
  pull_request:

permissions: {}

jobs:
  test:
    name: Main
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Benchmarks repository
        uses: actions/checkout@v3
        with:
          repository: finphie/Benchmarks
          path: Benchmarks
          token: ${{ secrets.SYNC_DOTFILES_PAT }}

      - run: |
          cd Benchmarks
          echo -n > empty.txt

      - name: Create PR
        uses: finphie/Actions/.github/actions/create-pull-request@main
        with:
          path: Benchmarks
          commit-message: Test commit
          branch: t
          labels: |
            performance
            refactor

  test-a:
    name: Main
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
      repository-projects: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - run: echo -n > empty.txt

      - name: Create PR
        uses: ./.github/actions/create-pull-request
        with:
          commit-message: Test commit
          branch: t
          labels: |
            performance
            refactor
