name: Update repository.json

on:
  workflow_call:
    secrets:
      GITHUB_TOKEN:
        required: true

permissions:
  contents: write

jobs:
  main:
    name: Main
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Get ProjectIdentifier
        id: project-identifier
        shell: pwsh
        run: |
          $lines = dotnet msbuild -nologo -target:GetProjectIdentifier

          'lines<<EOF' | Out-File $Env:GITHUB_OUTPUT -Append
          $lines | Out-File $Env:GITHUB_OUTPUT -Append
          'EOF' | Out-File $Env:GITHUB_OUTPUT -Append

      # 実行にはPowerShell 7.3以上が必要。
      - name: Update PowerShell
        working-directory: ${{ runner.temp }}
        run: |
          wget -q "https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/packages-microsoft-prod.deb"
          sudo dpkg -i packages-microsoft-prod.deb
          sudo apt-get install -y powershell

      - name: Update repository.json
        uses: finphie/Actions/.github/actions/update-repository-json@main
        with:
          solution-name: ${{ github.event.repository.name }}
          projects: ${{ steps.project-identifier.outputs.lines }}

      - name: Git diff
        id: diff
        continue-on-error: true
        run: |
          git add -N .
          git diff --name-only --exit-code

      - name: Git push
        if: steps.diff.outputs.outcome == 'failure'
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add .
          git commit -m 'Update repository.json'
          git push
