name: Upload artifacts (.NET)

on:
  workflow_call:
    inputs:
      dotnet-version:
        description: インストールする.NET SDKバージョン。
        required: false
        type: string
        default: 10.0.100-preview.6.25358.103
      runs-on:
        description: ランナー環境。
        required: false
        type: string
        default: ubuntu-latest
      project:
        description: プロジェクト名。
        required: true
        type: string
      target-platform-identifier:
        description: プラットフォーム識別子。
        required: false
        type: string
        default: none
      target-platform-version:
        description: プラットフォームバージョンを表す文字列。
        required: false
        type: string
        default: null
      os:
        description: OSの名前。（ランタイム識別子）
        required: true
        type: string
      architecture:
        description: アーキテクチャ名。（ランタイム識別子）
        required: true
        type: string
      workload-restore:
        description: dotnet workload restoreを実行するかどうか。
        required: false
        type: boolean
        default: false
      version:
        description: バージョンを表す文字列。
        required: true
        type: string
      suffix:
        description: アップロードする成果物名の末尾に追加する文字列。
        required: false
        type: string
        default: null

permissions: {}

env:
  OUTPUT_DIRECTORY: publish
  OUTPUT_FILE_NAME: ${{ inputs.suffix != '' && format('{0}_{1}', inputs.project, inputs.suffix) || inputs.project }}
  OUTPUT_FILE_EXTENSION: ${{ (startsWith(inputs.os, 'win') || startsWith(inputs.os, 'osx')) && 'zip' || 'tar.gz' }}
  RETENTION_DAYS: 1

jobs:
  main:
    name: >-
      ${{ inputs.project }} -
      ${{ (startsWith(inputs.os, 'win') && 'windows') || (startsWith(inputs.os, 'osx') && 'macos') || 'linux' }}(${{ inputs.architecture }})
    runs-on: ${{ inputs.runs-on }}
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: .NET Publish
        uses: finphie/Actions/.github/actions/dotnet-publish@main
        with:
          dotnet-version: ${{ inputs.dotnet-version }}
          project: ${{ inputs.project }}
          version: ${{ inputs.version }}
          target-platform-identifier: ${{ inputs.target-platform-identifier }}
          target-platform-version: ${{ inputs.target-platform-version }}
          runtime: ${{ inputs.os }}-${{ inputs.architecture }}
          workload-restore: ${{ inputs.workload-restore }}
          output-directory: ${{ env.OUTPUT_DIRECTORY }}

      - name: Compress archive
        uses: finphie/Actions/.github/actions/compress-archive@main
        with:
          path: ${{ env.OUTPUT_DIRECTORY }}
          type: ${{ env.OUTPUT_FILE_EXTENSION == 'zip' && 'zip' || 'gzip' }}
          destination-path: ${{ runner.temp }}/${{ env.OUTPUT_FILE_NAME }}.${{ env.OUTPUT_FILE_EXTENSION }}

      - name: Upload artifacts
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: ${{ env.OUTPUT_FILE_NAME }}
          path: ${{ runner.temp }}/${{ env.OUTPUT_FILE_NAME }}.${{ env.OUTPUT_FILE_EXTENSION }}
          retention-days: ${{ env.RETENTION_DAYS }}
