name: Upload NuGet library

on:
  workflow_call:
    inputs:
      dotnet-version:
        description: インストールする.NET SDKバージョン。
        required: false
        type: string
        default: 10.0.100-rc.1.25451.107
      version:
        description: バージョンを表す文字列。
        required: true
        type: string
      release:
        description: 安定版リリースかどうか。
        required: true
        type: boolean
    secrets:
      AZURE_ARTIFACT_PAT:
        description: 「Packaging」スコープの読み書きを許可したAzure DevOps Personal Access Token。
        required: true

permissions: {}

env:
  OUTPUT_DIRECTORY: pack

jobs:
  main:
    name: Push(NuGet)
    runs-on: windows-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: .NET Pack
        id: pack
        uses: finphie/Actions/.github/actions/dotnet-pack@main
        with:
          dotnet-version: ${{ inputs.dotnet-version }}
          version: ${{ inputs.version }}
          output-directory: ${{ env.OUTPUT_DIRECTORY }}

      - name: Push(Azure Artifacts)
        if: steps.pack.outputs.success == 'true'
        shell: pwsh
        run: |
          dotnet nuget update source $Env:SOURCE --username ${{ github.repository_owner }} --password $Env:TOKEN
          dotnet nuget push "${{ env.OUTPUT_DIRECTORY }}/**/*.nupkg" --api-key $Env:TOKEN --skip-duplicate --source $Env:SOURCE
        env:
          SOURCE: Azure
          TOKEN: ${{ secrets.AZURE_ARTIFACT_PAT }}

      - name: NuGet Login
        if: steps.pack.outputs.success == 'true' && inputs.release
        uses: NuGet/login@d22cc5f58ff5b88bf9bd452535b4335137e24544 # v1
        id: login
        with:
          user: ${{ github.repository_owner }}

      - name: Push(NuGet)
        if: steps.pack.outputs.success == 'true' && inputs.release
        shell: pwsh
        run: dotnet nuget push "${{ env.OUTPUT_DIRECTORY }}/**/*.nupkg" --api-key $Env:TOKEN --skip-duplicate --source $Env:SOURCE
        env:
          SOURCE: NuGet
          TOKEN: ${{ steps.login.outputs.NUGET_API_KEY }}
