name: Upload NuGet library

on:
  workflow_call:
    inputs:
      dotnet-version:
        description: インストールする.NET SDKバージョン。
        required: false
        type: string
        default: 7.0.x
      version:
        description: バージョンを表す文字列。
        required: true
        type: string
      release:
        description: 安定版リリースかどうか。
        required: true
        type: boolean
    secrets:
      AZURE_ARTIFACT_PAT:
        description: 「Packaging」スコープの読み書きを許可したAzure DevOps Personal Access Token。
        required: true
      NUGET_API_KEY:
        description: 「Push」スコープを許可したNuGet APIキー。
        required: true

permissions: {}

env:
  OUTPUT_DIRECTORY: pack

jobs:
  main:
    name: Push(NuGet)
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: .NET Pack
        id: pack
        uses: finphie/Actions/.github/actions/dotnet-pack@main
        with:
          dotnet-version: ${{ inputs.dotnet-version }}
          version: ${{ inputs.version }}
          output-directory: ${{ env.OUTPUT_DIRECTORY }}

      - name: Push(Azure Artifacts)
        if: steps.pack.outputs.success == 'true'
        shell: pwsh
        run: |
          dotnet nuget add source $Env:SOURCE_URL --name $Env:SOURCE --username $Env:GITHUB_ACTOR --password $Env:TOKEN
          dotnet nuget push "${{ env.OUTPUT_DIRECTORY }}/**/*.nupkg" --api-key $Env:TOKEN --skip-duplicate --source $Env:SOURCE
        env:
          SOURCE: Azure Artifacts
          SOURCE_URL: 'https://pkgs.dev.azure.com/finphie/Main/_packaging/DotNet/nuget/v3/index.json'
          TOKEN: ${{ secrets.AZURE_ARTIFACT_PAT }}

      - name: Push(NuGet)
        if: steps.pack.outputs.success == 'true' && inputs.release
        shell: pwsh
        run: dotnet nuget push "${{ env.OUTPUT_DIRECTORY }}/**/*.nupkg" --api-key $Env:TOKEN --skip-duplicate --source $Env:SOURCE_URL
        env:
          SOURCE_URL: 'https://api.nuget.org/v3/index.json'
          TOKEN: ${{ secrets.NUGET_API_KEY }}
