name: Upload artifacts (.NET)

on:
  workflow_call:
    inputs:
      project:
        description: プロジェクト名。
        required: true
        type: string
      platform:
        description: プラットフォーム名。console/windows/android/server/browserのいずれか。
        required: true
        type: string
      architecture:
        description: アーキテクチャ名。x64/arm64/wasmのいずれか。
        required: false
        type: string
      version:
        description: バージョンを表す文字列。
        required: true
        type: string
      suffix:
        description: アップロードする成果物名の末尾に追加する文字列。
        required: true
        type: string

permissions: {}

env:
  DOTNET_VERSION: '7.0'
  WINDOWS_TARGET_PLATFORM_VERSION: '10.0.19041.0'
  ANDROID_TARGET_SDK_VERSION: '32.0'
  OUTPUT_DIRECTORY: publish
  OUTPUT_FILE_NAME: ${{ inputs.project }}_${{ inputs.suffix }}_${{ inputs.architecture }}
  RETENTION_DAYS: 1

jobs:
  main:
    name: Upload artifacts
    runs-on: ${{ inputs.platform != 'browser' && 'windows-latest' || 'ubuntu-latest' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: .NET Publish
        uses: finphie/Actions/.github/actions/dotnet-publish@main
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          project: ${{ inputs.project }}
          version: ${{ inputs.version }}
          target-platform-identifier: ${{ (inputs.platform == 'windows' || inputs.platform == 'android') && inputs.platform || 'none' }}
          target-platform-version: ${{ (inputs.platform == 'windows' && env.WINDOWS_TARGET_PLATFORM_VERSION) || (inputs.platform == 'android' && env.ANDROID_TARGET_SDK_VERSION) || '' }}
          runtime: ${{ (inputs.platform == 'console' || inputs.platform == 'windows' || inputs.platform == 'server') && 'win10' || inputs.platform }}-${{ inputs.architecture }}
          workload-restore: ${{ inputs.platform == 'windows' || inputs.platform == 'android' || inputs.platform == 'browser' }}
          output-directory: ${{ env.OUTPUT_DIRECTORY }}

      - name: Compress archive
        uses: finphie/Actions/.github/actions/compress-archive@main
        with:
          path: ${{ env.OUTPUT_DIRECTORY }}
          destination-path: ${{ runner.temp }}/${{ env.OUTPUT_FILE_NAME }}.zip

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.OUTPUT_FILE_NAME }}
          path: ${{ runner.temp }}
          retention-days: ${{ env.RETENTION_DAYS }}
