name: Upload NuGet library

on:
  workflow_call:
    inputs:
      version:
        description: バージョンを表す文字列。
        required: true
        type: string
      release:
        description: 安定版リリースかどうか。
        required: true
        type: boolean
    secrets:
      AZURE_ARTIFACT_PAT:
        description: 「Packaging」スコープの読み書きを許可したAzure DevOps Personal Access Token。
        required: true
      NUGET_API_KEY:
        description: 「Push」スコープを許可したNuGet APIキー。
        required: true

permissions: {}

env:
  OUTPUT_DIRECTORY: pack

jobs:
  main:
    name: Push(NuGet)
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: .NET Pack
        id: pack
        uses: finphie/Actions/.github/actions/dotnet-pack@main
        with:
          version: ${{ inputs.version }}

      - name: Push(Azure Artifacts)
        if: steps.pack.outputs.success == 'true'
        run: |
          dotnet nuget add source $SOURCE_URL --name "$SOURCE" --user "$GITHUB_ACTOR" --password "$TOKEN"
          dotnet nuget push "./${{ env.OUTPUT_DIRECTORY }}/*.nupkg" --api-key "$TOKEN" --skip-duplicate --source "$SOURCE"
        env:
          SOURCE: Azure Artifacts
          SOURCE_URL: 'https://pkgs.dev.azure.com/finphie/Main/_packaging/DotNet/nuget/v3/index.json'
          TOKEN: ${{ secrets.AZURE_ARTIFACT_PAT }}

      - name: Push(NuGet)
        if: steps.pack.outputs.success == 'true' && inputs.release == 'true'
        run: dotnet nuget push "./${{ env.OUTPUT_DIRECTORY }}/*.nupkg" --api-key "$TOKEN" --skip-duplicate --source "$SOURCE_URL"
        env:
          SOURCE_URL: 'https://api.nuget.org/v3/index.json'
          TOKEN: ${{ secrets.NUGET_API_KEY }}
